[build]
  command = "docker run -d --name chat-gpt -p 8899:8899 -e PUID=0 -e PGID=0 -e TZ=Asia/Shanghai -e PANDORA_SERVER=0.0.0.0:8899 -e PANDORA_CLOUD=cloud -e PANDORA_ACCESS_TOKEN= --restart always pengzhile/pandora"
